export const userConstants={
    REGISTER_REQUEST : "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS : "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE : "USERS_REGISTER_FAILURE",

    LOGIN_REQUEST : "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS : "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE : "USERS_LOGIN_FAILURE",

    LOGOUT : "USERS_LOGOUT",

    SENDOTP_SUCCESS : "USERS_OTPSEND_SUCCESS",
    SENDOTP_FAILURE : "USERS_OTPSEND_FAILURE",
    SENDOTP_REQUEST : "USERS_OTPSEND_REQUEST",

    GETOTP_SUCCESS : "USERS_OTPGET_SUCCESS",
    GETOTP_FAILURE : "USERS_OTPGET_FAILURE",
    GETOTP_REQUEST : "USERS_OTPGET_REQUEST",
}